### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by nikola2radar** [radar2go/radar-beta#1]
Test

**Comment by mturjak** [comment]
=)

**Comment by nikola2radar** [comment]
HejTo sem ti se hotel povedat.Sem videl da si dodal pri filtru friends,favourite im frends&favourites.Mislim da bi bilo boljse in bolj zgodno da je to v filtru na zacetni strani.Imas nearast first, latest first ij se dodaa friends in favourite.

Zdi se mi bolj enostanvno in prakticno da ko E imamo ta hiter iskalnik da tukaj izberes da hoces videti samo poste prijateljev?Kaj mislisLp
Sent from Yahoo Mail on Android 

  On нед, дец 27, 2015 at 18:01, Martin Turjaknotifications@github.com wrote:  
Closed #1.

**Comment by nikola2radar** [comment]
Se enkrat jazSem mal gledal whats my urgent agentIn ne dela fajn...Otprem na chtome un mi pise da sem na mozili. Tko da bom posiljal un drugi link ki sem ti ga poslal na,skype.Tebi urgentagent dela ok?Lp
Sent from Yahoo Mail on Android 

  On нед, дец 27, 2015 at 21:27, nikola nikolicnikolic.nikola@yahoo.com wrote:   HejTo sem ti se hotel povedat.Sem videl da si dodal pri filtru friends,favourite im frends&favourites.Mislim da bi bilo boljse in bolj zgodno da je to v filtru na zacetni strani.Imas nearast first, latest first ij se dodaa friends in favourite.

Zdi se mi bolj enostanvno in prakticno da ko E imamo ta hiter iskalnik da tukaj izberes da hoces videti samo poste prijateljev?Kaj mislisLp
Sent from Yahoo Mail on Android 

  On нед, дец 27, 2015 at 18:01, Martin Turjaknotifications@github.com wrote:  
Closed #1.
