### ISSUE TITLE
Allow pinning

### ISSUE THREAD

**Issue by nikola2radar** [radar2go/radar-beta#10]
A ni ta gumb samo za biznise?
Vse v vsem ce ni na voljo da lahko nekaj spreminjajo morda ni treba da je v setings

**Comment by mturjak** [comment]
Sem odstranil opcijo iz settingsov zaenktar. Tako da bom ta bug zaenkrat zaprl kot razrešen ... lahko pa potem enkrat naknadno dodamo opcijo samo za vendorje seveda (ker tako kot praviš drugje nima smisla), če slučajno kakim vendorjem ne bo pasalo, da jim ljudje pinnajo stvari.

**Comment by nikola2radar** [comment]
Super
