### ISSUE TITLE
Email notifikacija

### ISSUE THREAD

**Issue by nikola2radar** [radar2go/radar-beta#13]
Notifikacije odlicno delajo, mal jih je prevec :-)
En email dobimo ko moj najljjbsi bar objavi ponudbo..
2.ko zgrebam
3.ko potrdim regiatracijo

Predlog:
Ko zgrebam notifikacijo in ko potrdim rezervacijo- brez email notifikacije-notifikacija samo v aplikaciji.

**Comment by mturjak** [comment]
Sem umaknil pošiljanje emailov za svoja dejanja (grabljenje offerjev in potrditve offerjev)
