### ISSUE TITLE
Explorer bug

### ISSUE THREAD

**Issue by nikola2radar** [radar2go/radar-beta#17]
Ko na explorerju objavis ponudbo/moment ne pokaze objavo na  home page. 
Te iste objave pa pokaze na drugih iskalnikih.

Mozila/5.0(windows nt6.1; wow64; trident/7.0;rv;11.0) like Gecko

**Comment by nikola2radar** [comment]
zanimivo 
objava in brisanje postov ki ni delala na explorerju nedela
ko brisem kes ne dela ... in sem brisal vse zivo,  ko vse pobrisem pa zbrise post
potem sem eno po eno brisal in sem najde problem.

ko izbrisem
temporary internet files and websites files( copies of webpages,images, and media tat are saved for faster viewing) pa pobrise objavo ki sem jo pred tem pobrisal

**Comment by nikola2radar** [comment]
sem napacn objavil ampak isti problem
in za objavo in za brisanje vse se pokaze ko se izbrise
temporary internet files and websites files( copies of webpages,images, and media tat are saved for faster viewing

**Comment by mturjak** [comment]
Sem implementiral ene spremembe glede cachanja, ki bodo take situacije nekoliko izboljšale. Preveri, če je na webappu sedaj situacija kaj boljše ... in ali prikazuje spremembe (dodane in brisane poste).

# 

Modifications to the setup in `app.js` - that can be additionally tweaked:

``` javascript
 .config(['$httpProvider',
    function($httpProvider) {
      if (!$httpProvider.defaults.headers.get) {
        $httpProvider.defaults.headers.get = {};
      }

      $httpProvider.defaults.headers.get['If-Modified-Since'] = 'Mon, 26 Jul 1997 05:00:00 GMT';      
      $httpProvider.defaults.headers.get['Cache-Control'] = 'no-cache';
      $httpProvider.defaults.headers.get.Pragma = 'no-cache';
    }])
```

**TODO:** check if `$httpProvider` changes affect the `$resource` services provider, if not we might need to try modifying the `$resource` provider instead.

**Comment by nikola2radar** [comment]
Zrihtal si! Nic se ne prikazuje ampak objavla in brise poste brez tezave:-)
