### ISSUE TITLE
Mozila brisanje posta

### ISSUE THREAD

**Issue by nikola2radar** [radar2go/radar-beta#18]
Ne mores pobrisat svoj post
Mozila/5.0(windows nt6.1;wow64;rv:43.0) gexko/20100101 firefoz/43.0
Enako problem je na ezplorerju
Mozila/5.0 (winsows nt 6.1;wow64;trident/7.0;rc:11.0) lije gecko

**Comment by nikola2radar** [comment]
isto
temporary internet files and websites files( copies of webpages,images, and media tat are saved for faster viewing
ko pobrises se file izbrise

**Comment by mturjak** [comment]
to je problem s shranjevanjem API odgovora v cache ... sem odstranil cache z API klicev ... upam, da to odpravi težavo.
