### ISSUE TITLE
Bug/objava nomentov

### ISSUE THREAD

**Issue by nikola2radar** [radar2go/radar-beta#20]
Smo najdli telefon kje ne delajo objave
Lahko iz galerije uploudas sliko/video in potem vse stima.
Provlem je posneti iz app-a
To su podatci iz browserja ki jih imam
Mozila/5.0(linux;u;android4.4.2;htc_desire_610..kot49h)applewebkit/534.30(khtml,like gecko) version/4.0mob safari/534.30

Mozila/5.0(linux;android 4.4.2; htc desire 610 build/kot49h ) apolewebkit/537.36(khtml, like gecko) chrome/47.0.2526.83

**Comment by mturjak** [comment]
Closing as duplicate of issue #19
