### ISSUE TITLE
Safari-iphone6

### ISSUE THREAD

**Issue by nikola2radar** [radar2go/radar-beta#27]
Ko je pristopila radarju je dobila obvestilo da rabi omogociti dostop do lokacije in je opcija ok katero je izbrala.
Ampak lokacija nije deljena
Predvidevam da v nastavitvah  safarija ni dovoljeno deljenje lokacije( spomnem se da meni vikler ni delal kjer je v nastavitvah bilo blokirano deljenje lokacije)
Ona ni znala zrihtat, jaz sem tudi iskal na netu ampak nisem najdrl
Na anroidu dobim obvestilo kako da pridem do opcije da omogocim dostop, lahko enako naredis za iphone.
Predvidevam da je to problem
Ce ni, imam vsw podatke o njenem safariju

**Comment by nikola2radar** [comment]
Sem instaloral safari browser na moj telefon.
In me je prasal na zacetku za lokacijo. In me pustil v app. Sem slikal innje vse slo ok dokler nisem hotel objavit posy takrat me je spet vprasal z lokacijo. Sem sel . Settings in tam pise da dovoljuje pristop lokaciji....
Vem da safari ni za.android ampak sem downlodal app na svoj telefon

**Comment by mturjak** [comment]
To je v resnici problem obveščanja o iskanju lokacije ... to obdelamo pod drugo točko naslednjega issue #28, tako da bom zaenkrat ta issue zaprl.
