### ISSUE TITLE
Obvestilo pri registraciji

### ISSUE THREAD

**Issue by nikola2radar** [radar2go/radar-beta#28]
Na veliki vecini naprav radar deluje :-)
Tisto kaj vecini dela tezavo po registraciji
1. Ko se registrirajo morajo dobiti obvestilo da je nujno da potrdijo registracijo z emailom kjer ce ne potrdijo ne morejo objavljat.
Enima gre obvestilo v spam pa ne dobivajo notifikacijo.
2. Super si naredil da ce browser ne dovoli delitev lokacije pise da za uporabo radarja rabijo lokacijo ampak ljudje mislijo  da ce  pritisnejo ok bo delalo. In vecina ljudi ne ve kako in kje nastimat da dovolijo lociranje in to je problem za nas.
Vecina brovserjev v originalnih nastavitvah ima isklopljeno delenje lokacije

Sem na parih telefonov testiral in potem mores narediti naslednje
Nastimas lokacijo
Izbrises kes in komaj takrat te vprasa znova za lokacijo in lahko uporabljas app
Brez brisanja kesa te ne vprasa za delenje lokacije.

**Comment by mturjak** [comment]
1. Added a top-bar notification to point out that a confirmation email has been sent

**Comment by mturjak** [comment]
1.  - added a loader page that appears while radar2go is searching for current location
   - a link on the loader page to a modal info box explaining how to enable location service
