### ISSUE TITLE
Dodajanje prijateljev

### ISSUE THREAD

**Issue by nikola2radar** [radar2go/radar-beta#29]
Iskalnik ne najde vseh ljudi ki so na radarju.
Ali je dodajanje prijateljev omejeno z  daljavo?

**Comment by mturjak** [comment]
Iskanje prijateljev ni omejeno z daljavo. Ampak je še vedno imelo v iskalniku tudi username, ki pa ni več aktualen ... sem umaknil in sedaj bi moralo delovati.

**Comment by nikola2radar** [comment]
Dela :-(

**Comment by nikola2radar** [comment]
:-))))
