### ISSUE TITLE
New explorer bug

### ISSUE THREAD

**Issue by nikola2radar** [radar2go/radar-beta#34]
Mozila/5.0(compatible;MSIE 9.0;windows NT 6.1;WOW64;TRIDENT/5.0)
 Ko kliknes na katerokoli opcijo te vrze na belo stran kje so nastete funkcionalnosti(slika na emailu)

![IE bug](http://i.imgur.com/dCDMFuj.png)

**Comment by mturjak** [comment]
To je verjetno zato ker je v kodi še nekaj delčkov, ki so namenjeni debuganju sedaj med testiranjem aplikacije. Sem sedaj večino odstranil tako da je treba sedaj še enkrat preverit, če se je kaj izboljšalo.
Hvala!

# 

Removed some development related code and commented out console output

``` javascript
console.log();
```

which is supposed to break angularjs execution in IE based on:
[http://www.visualstudiogeeks.com/blog/angularjs/mvc/ie/angularjs-and-ie9/](http://www.visualstudiogeeks.com/blog/angularjs/mvc/ie/angularjs-and-ie9/)

**Comment by nikola2radar** [comment]
Koncno sem dobil informacijo glede tega buga
Je opravljen tko da lahko zapres

**Comment by nikola2radar** [comment]
Koncno sem dobil informacijo glede tega buga
Je opravljen tko da lahko zapres
