### ISSUE TITLE
Slika/video

### ISSUE THREAD

**Issue by nikola2radar** [radar2go/radar-beta#4]
Ljude moti da ko otprejo post ne morejo videti celo sliko(velja za mobitele) ko otpres fotko je fotka zumirana in jo ne vidis celo

**Comment by mturjak** [comment]
še sem dodajam poslane slike za inspiracijo:

![Imgur](http://i.imgur.com/0a7kFAs.png)  
![Imgur](http://i.imgur.com/7rpNtr1.png)  
![Imgur](http://i.imgur.com/JOYsyzj.png)  
![Imgur](http://i.imgur.com/6CSocJd.png)
