### ISSUE TITLE
Filter

### ISSUE THREAD

**Issue by nikola2radar** [radar2go/radar-beta#5]
Vec ljudi danes so imeli pripombo na filter.
Apply filter jim ni jasen.
Predlog je da so kategorije takoj na vrhu in da so oznacene vse kljukice( rdeci kvadratek) ce zelijo izbrati neke  potem odkljukajo katere ne zelijo.

Pa se tole. Ni jim jasen x mislijo da a tem poncijo  naatavotve. Jim je bolj intuiticno da je gumb  ki potrdi filtre in jih pelje na  home page

Se tole. Petimi od danes je bolj prirocno da poste prijateljev in favourite lahko filtrirajo . Home page( dodatek pri latest in Near me)

**Comment by nikola2radar** [comment]
Near me)

**Comment by mturjak** [comment]
Bom malo razmislil kako bi to najelegantneje rešili ... mogoče je najboljše narediti podobno kot smo imeli v prejšnjem designu, kjer je vse na prvi srani prikazano kot ikonice v vrstici s filtri in se izbira iz dropdown menijev namesto na posebni "filters" podstrani.

**Comment by nikola2radar** [comment]
Meni je boljse kot je zdaj vizualno.
Jaz bi samo na prvo stran dodal da lahko izberejo poste prijateljev in favourite
V filtru bi imel samo kateforije in aplly filter je gumb ki potrdi  spremembe in pelje na zacetno stran.
Lahko je tudi un zelen okrogel apply.
Sem razmisljal da bi mogoce dali vn opcijo da izberejo samo momente in ponudbe za enkrat.

Tko bi na filtru na zacetni strani imeli nearest first.latest first, frienda in favouritr in os tukaj ful hitro nastavis kaj si zelis.

Meni bi tole bilo najboljse ampak upostevam vsako tvoje mnenje

**Comment by mturjak** [comment]
Bom tako napravil
