### ISSUE TITLE
Notifikacije

### ISSUE THREAD

**Issue by nikola2radar** [radar2go/radar-beta#7]
To je moje osebno mnenje.
Kaj mislis ce bi notifikacije posiljali samo ko posiljas privat post(tko je ze sedaj) in samo ko biznis poslje ponudbo/ objavo samo foloverjem.
Na ta nacin bo manj notifikacij pa biznisi imajo potrebo da spodbujajo ljudje da jih followajo.

**Comment by mturjak** [comment]
Tako bi moralo že delovati ko biznis objavi nekaj (javno ali samo followerjem) bi morali notifikacijo dobiti le followerji (če to ne deluje potem bom označil to kod bug). Drugače si notificiran, če je privat sporočilo ali če te nekdo povabi nekam, ampak le si notificiran le če je tvoja zadnja lokacija v njihovi bližini (tako da je tudi notificiranje lokacijsko omejeno ... tukaj sva rekla, da bi mogoče naredila, da neglede na lokacijo lahko dobiš privat sporočilo ... ampak to lahko ta trenutek po moje še počaka).

Sem pa res po pomoti tako naredil, da si bil notificiran, če si prijatelj od nekoga in ki na post označi visibility na 'friends' ... to sem sedaj na hito popravil ... tako da si notificiran od prijateljev le ob privatnem postu. Upam, da to sedaj deluje.

**Comment by nikola2radar** [comment]
Super in ni bug!dobis od biznisa samo ce si jih oznacil kot najljubsi.
Je samo ideja . Kjer ce en kafe objavi pet ponudbi na dan is si alucajno bliz te moti.
Velika verjetnost je da lokal bo objavljal javno. In potem te ne moti notifikacija.
Ce je neka posebna pinudba samo za follocerje potem je nekaj posebnega.
Al pa setings notifikacije kje uredis ce zelis dobivati notifikaxije ali ne.
Samo ideja ni bug
Pa sw to
Na gmailu mi obvestila gtejo v spam v yahoo pa v redna sporocila.

**Comment by mturjak** [comment]
Ja ... pt da je samo za privat pri navadnih userjih je sedaj urejeno. Za vendorje pa bi potem naredili tako, da dobijo followerji vedno notifikacijo v aplikaciji ... email pa samo če je post za followerje. Sem dodal now issue #22 ... ker sem direktno izpostavil to situacijo.

**Comment by nikola2radar** [comment]
Super! Ce objavijo samo za favourite dobis notifikacijo in takrat je nekaj posebnega...
