### ISSUE TITLE
Potrdilo notifikacije

### ISSUE THREAD

**Issue by nikola2radar** [radar2go/radar-beta#9]
Super dela.
Tu su komentarji razlicni. Sedaj nimamo moznost da ce zamude lahko podaljsajo cas prihoda.
Moznost:
-rezervacija je aktivna dokler je ponudba aktivna
Vremenska crta je okviren cas v katerem bos prisel.
Kasneje lahko omogociva biznisom da izberejo ce zelijo vrrmensko crto
- se ena ideja je da bi biznisi dobili potrdilo prek sms-a ampak to ni opcija sedaj je pa za razmislek( v sms dobijejo notifikacijo iste vsebine kot email s linkok)

**Comment by mturjak** [comment]
Narejeno tako, da je grab veljaven do poteka ponudbe.
